### ISSUE TITLE
【建议】降低 puppeteer 依赖版本

### ISSUE THREAD

**Issue by Mcayear** [ahdg6/koishi-plugin-minecraft#1]
![image](https://github.com/ahdg6/koishi-plugin-minecraft/assets/48203962/635a153f-d68a-40d3-9885-69478e5b1073)
需要^3.5.0，但是ubuntu的puppeteer只支持到 3.4.11。

建议改为 ^3.0.2 以提供给更多设备使用。

**Comment by ahdg6** [comment]
事实上我根本没用到 puppeteer，package 删掉就好了

**Comment by ahdg6** [comment]
反馈一下0.6.3能用吗

**Comment by Mcayear** [comment]
koishi识别不到任何命令😟。可能我操作有误？
![JPEG_20230605_164807_858594667403297264](https://github.com/ahdg6/koishi-plugin-minecraft/assets/48203962/38473fb9-3353-44a6-8097-5cbf1b5774ed)

**Comment by ahdg6** [comment]
啊？看看日志

**Comment by ahdg6** [comment]
![图片](https://github.com/ahdg6/koishi-plugin-minecraft/assets/36436808/64cc0378-2d8e-4fba-8024-4448b07563bd)
我测试没问题，你要不发个日志?

**Comment by Mcayear** [comment]
```
2023-06-05 17:16:05 [I] app unload plugin minecraft:haz5ba
2023-06-05 17:16:07 [I] app apply plugin minecraft:haz5ba
2023-06-05 17:16:07 [W] app Error: Cannot find module './locales/zh-CN.yml'
                        Require stack:
                        - /koishi/node_modules/koishi-plugin-minecraft/lib/index.js
                        - /koishi/node_modules/@koishijs/loader/lib/index.js
                        - /koishi/node_modules/koishi/lib/worker/index.js
                            at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
                            at Module._load (node:internal/modules/cjs/loader:920:27)
                            at Module.require (node:internal/modules/cjs/loader:1141:19)
                            at require (node:internal/modules/cjs/helpers:110:18)
                            at Object.apply (/koishi/node_modules/koishi-plugin-minecraft/lib/index.js:38:27)
                            at /koishi/node_modules/cordis/lib/index.cjs:415:40
                            at MainScope.ensure (/koishi/node_modules/cordis/lib/index.cjs:257:18)
                            at MainScope.apply (/koishi/node_modules/cordis/lib/index.cjs:415:14)
                            at MainScope.start (/koishi/node_modules/cordis/lib/index.cjs:475:12)
                            at MainScope.restart (/koishi/node_modules/cordis/lib/index.cjs:235:10)
```

**Comment by ahdg6** [comment]
hmmm，推了个 0.6.4，刷新安装后应该就解决了，小问题
